import type { Metadata } from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Buddy Script",
  description: "Generated by create next app",
  icons: {
    icon: "/assets/images/logo-copy.svg",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        {/* Fonts */}
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
        <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;300;400;500;600;700;800&display=swap"
          rel="stylesheet"
        />

        {/* Bootstrap */}
        <link rel="stylesheet" href="/assets/css/bootstrap.min.css" />

        {/* Common Css */}
        <link rel="stylesheet" href="/assets/css/common.css" />

        {/* Custom Css */}
        <link rel="stylesheet" href="/assets/css/main.css" />

        {/* Responsive Css */}
        <link rel="stylesheet" href="/assets/css/responsive.css" />
      </head>
      <body suppressHydrationWarning>
        {children}
      </body>
    </html>
  );
}